language: php
php:
- 7.0
- 5.6
- 5.5
- 5.4
- 5.3
- hhvm
script: phpunit
before_script:
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - |
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
        composer global require "phpunit/phpunit=5.7.*"
      else
        composer global require "phpunit/phpunit=4.8.*"
      fi