language: php
dist: trusty

matrix:
  include:
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - php: 5.3
      dist: precise

script: phpunit
before_script:
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - |
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
        composer global require "phpunit/phpunit=5.7.*"
      else
        composer global require "phpunit/phpunit=4.8.*"
      fi
      echo phpunit --version